import { config } from '@/config';

type SitemapFile = {
  url: string;
  lastModified?: string | Date;
  changeFrequency?: 'always' | 'daily' | 'hourly' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority?: number;
};

export default async function sitemap(): Promise<SitemapFile[]> {
  try {
    // Class API
    const classResponse = await fetch(`${config.API_URL}/sitemap/class`);
    const { data: classData } = await classResponse.json();
    const classDataResponse: string[] = classData?.data ?? [];
    // Book API
    const bookResponse = await fetch(`${config.API_URL}/sitemap/book`);
    const { data: bookData } = await bookResponse.json();
    const bookDataResponse: string[] = bookData?.data ?? [];
    // Chapter API
    const chapterResponse = await fetch(`${config.API_URL}/sitemap/chapter`);
    const { data: chapterData } = await chapterResponse.json();
    const chapterDataResponse: string[] = chapterData?.data ?? [];
    // Heading API
    const headingResponse = await fetch(`${config.API_URL}/sitemap/heading`);
    const { data: headingData } = await headingResponse.json();
    const headingDataResponse: string[] = headingData?.data ?? [];
    // Subheading API
    const subHeadingResponse = await fetch(`${config.API_URL}/sitemap/subHeading`);
    const { data: subHeadingData } = await subHeadingResponse.json();
    const subHeadingDataResponse: string[] = subHeadingData?.data ?? [];
    // Mcqs API
    const mcqsResponse = await fetch(`${config.API_URL}/sitemap/mcqs`);
    const { data: mcqsData } = await mcqsResponse.json();
    const mcqsDataResponse: string[] = mcqsData?.data ?? [];

    // Combine all data
    const ApiData = [
      ...classDataResponse,
      ...bookDataResponse,
      ...chapterDataResponse,
      ...headingDataResponse,
      ...subHeadingDataResponse,
      ...mcqsDataResponse,
    ];

    const RoutesApiData: SitemapFile[] = ApiData.map(data => ({
      url: data,
      lastModified: new Date().toISOString(),
      priority: 0.8,
      changeFrequency: 'weekly' as const,
    }));

    const RoutesData: SitemapFile[] = data.map(data => ({
      url: `${config.Frontend_URL}/${data}/`,
      lastModified: new Date().toISOString(),
      priority: 0.8,
      changeFrequency: 'weekly' as const,
    }));

    // Combine all routes
    const routes: SitemapFile[] = [
      {
        url: `${config.Frontend_URL}/`,
        lastModified: new Date().toISOString(),
        priority: 1,
        changeFrequency: 'always',
      },
      ...RoutesData,
      ...RoutesApiData,
    ];

    return routes;
  } catch (error) {
    console.error('Error', error);
    return [];
  }
}

const singleroute = [
  'class-9',
  'class-10',
  'class-11',
  'class-12',
  'vu',
  'book-point',
  'online-test-point',
  'date-sheet',
  'result',
  'notes',
  'past-paper',
  'pairing-scheme',
  'about-us',
  'contact-us',
  'disclaimer',
  'faqs',
  'report-a-bug',
  'user-experience',
  'terms-and-conditions',
  'request-feature',
  'explore-topics',
  'jobs-opportunities',
  'study-group',
  'success-stories',
];

const class9route = [
  'class-9/books',
  'class-9/books/punjab-board-physics',
  'class-9/books/punjab-board-physics/english-medium',
  'class-9/books/punjab-board-physics/urdu-medium',
  'class-9/books/punjab-board-chemistry',
  'class-9/books/punjab-board-chemistry/english-medium',
  'class-9/books/punjab-board-chemistry/urdu-medium',
  'class-9/books/punjab-board-biology',
  'class-9/books/punjab-board-biology/english-medium',
  'class-9/books/punjab-board-biology/urdu-medium',
  'class-9/books/punjab-board-math',
  'class-9/books/punjab-board-math/english-medium',
  'class-9/books/punjab-board-math/urdu-medium',
  'class-9/books/punjab-board-computer-science',
  'class-9/books/punjab-board-computer-science/english-medium',
  'class-9/books/punjab-board-computer-science/urdu-medium',
  'class-9/books/punjab-board-economics',
  'class-9/books/punjab-board-english',
  'class-9/books/punjab-board-general-math',
  'class-9/books/punjab-board-general-math/english-medium',
  'class-9/books/punjab-board-general-math/urdu-medium',
  'class-9/books/punjab-board-ikhlaqiat',
  'class-9/books/punjab-board-islamiyat',
  'class-9/books/punjab-board-pak-study',
  'class-9/books/punjab-board-pak-study/english-medium',
  'class-9/books/punjab-board-pak-study/urdu-medium',
  'class-9/books/punjab-board-tarjuma-tul-quran',
  'class-9/books/punjab-board-urdu',

  'class-9/date-sheet',
  'class-9/date-sheet/bahawalpur-board',
  'class-9/date-sheet/dg-khan-board',
  'class-9/date-sheet/faisalabad-board',
  'class-9/date-sheet/gujranwala-board',
  'class-9/date-sheet/lahore-board',
  'class-9/date-sheet/multan-board',
  'class-9/date-sheet/rawalpindi-board',
  'class-9/date-sheet/sahiwal-board',
  'class-9/date-sheet/sargodha-board',

  'class-9/online-test',
  'class-9/online-test/physics',
  'class-9/online-test/physics/chapter-1',
  'class-9/online-test/physics/chapter-2',
  'class-9/online-test/physics/chapter-3',
  'class-9/online-test/physics/chapter-4',
  'class-9/online-test/physics/chapter-5',
  'class-9/online-test/physics/chapter-6',
  'class-9/online-test/physics/chapter-7',
  'class-9/online-test/physics/chapter-8',
  'class-9/online-test/physics/chapter-9',
  'class-9/online-test/biology',
  'class-9/online-test/biology/chapter-1',
  'class-9/online-test/biology/chapter-2',
  'class-9/online-test/biology/chapter-3',
  'class-9/online-test/biology/chapter-4',
  'class-9/online-test/biology/chapter-5',
  'class-9/online-test/biology/chapter-6',
  'class-9/online-test/biology/chapter-7',
  'class-9/online-test/biology/chapter-8',
  'class-9/online-test/biology/chapter-9',
  'class-9/online-test/chemistry',
  'class-9/online-test/chemistry/chapter-1',
  'class-9/online-test/chemistry/chapter-2',
  'class-9/online-test/chemistry/chapter-3',
  'class-9/online-test/chemistry/chapter-4',
  'class-9/online-test/chemistry/chapter-5',
  'class-9/online-test/chemistry/chapter-6',
  'class-9/online-test/chemistry/chapter-7',
  'class-9/online-test/chemistry/chapter-8',

  'class-9/notes',
  'class-9/notes/punjab-board-physics',
  'class-9/notes/punjab-board-chemistry',
  'class-9/notes/punjab-board-biology',

  'class-9/pairing-scheme',
  'class-9/pairing-scheme/punjab-board',
  'class-9/pairing-scheme/punjab-board/biology',
  'class-9/pairing-scheme/punjab-board/chemistry',
  'class-9/pairing-scheme/punjab-board/physics',
  'class-9/pairing-scheme/punjab-board/math',

  'class-9/past-paper',
  'class-9/past-paper/faisalabad-board-biology',
  'class-9/past-paper/faisalabad-board-chemistry',
  'class-9/past-paper/faisalabad-board-physics',
  'class-9/past-paper/lahore-board-biology',
  'class-9/past-paper/lahore-board-chemistry',
  'class-9/past-paper/lahore-board-physics',

  'class-9/result',
  'class-9/result/bahawalpur-board',
  'class-9/result/dg-khan-board',
  'class-9/result/faisalabad-board',
  'class-9/result/gujranwala-board',
  'class-9/result/lahore-board',
  'class-9/result/multan-board',
  'class-9/result/rawalpindi-board',
  'class-9/result/sahiwal-board',
  'class-9/result/sargodha-board',
];

const class10route = [
  'class-10/books',
  'class-10/books/punjab-board-physics',
  'class-10/books/punjab-board-physics/english-medium',
  'class-10/books/punjab-board-physics/urdu-medium',
  'class-10/books/punjab-board-chemistry',
  'class-10/books/punjab-board-chemistry/english-medium',
  'class-10/books/punjab-board-chemistry/urdu-medium',
  'class-10/books/punjab-board-biology',
  'class-10/books/punjab-board-biology/english-medium',
  'class-10/books/punjab-board-biology/urdu-medium',
  'class-10/books/punjab-board-math',
  'class-10/books/punjab-board-math/english-medium',
  'class-10/books/punjab-board-math/urdu-medium',
  'class-10/books/punjab-board-computer-science',
  'class-10/books/punjab-board-computer-science/english-medium',
  'class-10/books/punjab-board-computer-science/urdu-medium',
  'class-10/books/punjab-board-economics',
  'class-10/books/punjab-board-english',
  'class-10/books/punjab-board-general-math',
  'class-10/books/punjab-board-general-math/english-medium',
  'class-10/books/punjab-board-general-math/urdu-medium',
  'class-10/books/punjab-board-ikhlaqiat',
  'class-10/books/punjab-board-islamiyat',
  'class-10/books/punjab-board-pak-study',
  'class-10/books/punjab-board-pak-study/english-medium',
  'class-10/books/punjab-board-pak-study/urdu-medium',
  'class-10/books/punjab-board-tarjuma-tul-quran',
  'class-10/books/punjab-board-urdu',

  'class-10/date-sheet',
  'class-10/date-sheet/bahawalpur-board',
  'class-10/date-sheet/dg-khan-board',
  'class-10/date-sheet/faisalabad-board',
  'class-10/date-sheet/gujranwala-board',
  'class-10/date-sheet/lahore-board',
  'class-10/date-sheet/multan-board',
  'class-10/date-sheet/rawalpindi-board',
  'class-10/date-sheet/sahiwal-board',
  'class-10/date-sheet/sargodha-board',

  'class-10/notes',
  'class-10/notes/punjab-board-physics',
  'class-10/notes/punjab-board-chemistry',
  'class-10/notes/punjab-board-biology',

  'class-10/online-test',
  'class-10/online-test/physics',
  'class-10/online-test/physics/chapter-1',
  'class-10/online-test/physics/chapter-2',
  'class-10/online-test/physics/chapter-3',
  'class-10/online-test/physics/chapter-4',
  'class-10/online-test/physics/chapter-5',
  'class-10/online-test/physics/chapter-6',
  'class-10/online-test/physics/chapter-7',
  'class-10/online-test/physics/chapter-8',
  'class-10/online-test/physics/chapter-9',
  'class-10/online-test/biology',
  'class-10/online-test/biology/chapter-1',
  'class-10/online-test/biology/chapter-2',
  'class-10/online-test/biology/chapter-3',
  'class-10/online-test/biology/chapter-4',
  'class-10/online-test/biology/chapter-5',
  'class-10/online-test/biology/chapter-6',
  'class-10/online-test/biology/chapter-7',
  'class-10/online-test/biology/chapter-8',
  'class-10/online-test/biology/chapter-9',
  'class-10/online-test/chemistry',
  'class-10/online-test/chemistry/chapter-1',
  'class-10/online-test/chemistry/chapter-2',
  'class-10/online-test/chemistry/chapter-3',
  'class-10/online-test/chemistry/chapter-4',
  'class-10/online-test/chemistry/chapter-5',
  'class-10/online-test/chemistry/chapter-6',
  'class-10/online-test/chemistry/chapter-7',
  'class-10/online-test/chemistry/chapter-8',

  'class-10/pairing-scheme',
  'class-10/pairing-scheme/punjab-board',
  'class-10/pairing-scheme/punjab-board/biology',
  'class-10/pairing-scheme/punjab-board/chemistry',
  'class-10/pairing-scheme/punjab-board/physics',
  'class-10/pairing-scheme/punjab-board/math',

  'class-10/past-paper',
  'class-10/past-paper/faisalabad-board-biology',
  'class-10/past-paper/faisalabad-board-chemistry',
  'class-10/past-paper/faisalabad-board-physics',
  'class-10/past-paper/lahore-board-biology',
  'class-10/past-paper/lahore-board-chemistry',
  'class-10/past-paper/lahore-board-physics',

  'class-10/result',
  'class-10/result/bahawalpur-board',
  'class-10/result/dg-khan-board',
  'class-10/result/faisalabad-board',
  'class-10/result/gujranwala-board',
  'class-10/result/lahore-board',
  'class-10/result/multan-board',
  'class-10/result/rawalpindi-board',
  'class-10/result/sahiwal-board',
  'class-10/result/sargodha-board',
];

const class11route = [
  'class-11/books',
  'class-11/books/punjab-board-physics',
  'class-11/books/punjab-board-chemistry',
  'class-11/books/punjab-board-biology',
  'class-11/books/punjab-board-math',
  'class-11/books/punjab-board-computer-science',
  'class-11/books/punjab-board-english',
  'class-11/books/punjab-board-islamiyat',
  'class-11/books/punjab-board-tarjuma-tul-quran',
  'class-11/books/punjab-board-urdu',

  'class-11/date-sheet',
  'class-11/date-sheet/bahawalpur-board',
  'class-11/date-sheet/dg-khan-board',
  'class-11/date-sheet/faisalabad-board',
  'class-11/date-sheet/gujranwala-board',
  'class-11/date-sheet/lahore-board',
  'class-11/date-sheet/multan-board',
  'class-11/date-sheet/rawalpindi-board',
  'class-11/date-sheet/sahiwal-board',
  'class-11/date-sheet/sargodha-board',

  'class-11/notes',
  'class-11/notes/punjab-board-physics',
  'class-11/notes/punjab-board-chemistry',
  'class-11/notes/punjab-board-biology',

  'class-11/online-test',
  'class-11/online-test/physics',
  'class-11/online-test/physics/chapter-1',
  'class-11/online-test/physics/chapter-2',
  'class-11/online-test/physics/chapter-3',
  'class-11/online-test/physics/chapter-4',
  'class-11/online-test/physics/chapter-5',
  'class-11/online-test/physics/chapter-6',
  'class-11/online-test/physics/chapter-7',
  'class-11/online-test/physics/chapter-8',
  'class-11/online-test/physics/chapter-9',
  'class-11/online-test/physics/chapter-10',
  'class-11/online-test/physics/chapter-11',
  'class-11/online-test/biology',
  'class-11/online-test/biology/chapter-1',
  'class-11/online-test/biology/chapter-2',
  'class-11/online-test/biology/chapter-3',
  'class-11/online-test/biology/chapter-4',
  'class-11/online-test/biology/chapter-5',
  'class-11/online-test/biology/chapter-6',
  'class-11/online-test/biology/chapter-7',
  'class-11/online-test/biology/chapter-8',
  'class-11/online-test/biology/chapter-9',
  'class-11/online-test/biology/chapter-10',
  'class-11/online-test/biology/chapter-11',
  'class-11/online-test/biology/chapter-12',
  'class-11/online-test/biology/chapter-13',
  'class-11/online-test/biology/chapter-14',
  'class-11/online-test/chemistry',
  'class-11/online-test/chemistry/chapter-1',
  'class-11/online-test/chemistry/chapter-2',
  'class-11/online-test/chemistry/chapter-3',
  'class-11/online-test/chemistry/chapter-4',
  'class-11/online-test/chemistry/chapter-5',
  'class-11/online-test/chemistry/chapter-6',
  'class-11/online-test/chemistry/chapter-7',
  'class-11/online-test/chemistry/chapter-8',
  'class-11/online-test/chemistry/chapter-9',
  'class-11/online-test/chemistry/chapter-10',
  'class-11/online-test/chemistry/chapter-11',

  'class-11/pairing-scheme',
  'class-11/pairing-scheme/punjab-board',
  'class-11/pairing-scheme/punjab-board/biology',
  'class-11/pairing-scheme/punjab-board/chemistry',
  'class-11/pairing-scheme/punjab-board/physics',
  'class-11/pairing-scheme/punjab-board/math',

  'class-11/past-paper',
  'class-11/past-paper/faisalabad-board-biology',
  'class-11/past-paper/faisalabad-board-chemistry',
  'class-11/past-paper/faisalabad-board-physics',
  'class-11/past-paper/lahore-board-biology',
  'class-11/past-paper/lahore-board-chemistry',
  'class-11/past-paper/lahore-board-physics',

  'class-11/result',
  'class-11/result/bahawalpur-board',
  'class-11/result/dg-khan-board',
  'class-11/result/faisalabad-board',
  'class-11/result/gujranwala-board',
  'class-11/result/lahore-board',
  'class-11/result/multan-board',
  'class-11/result/rawalpindi-board',
  'class-11/result/sahiwal-board',
  'class-11/result/sargodha-board',
];

const class12route = [
  'class-12/books',
  'class-12/books/punjab-board-physics',
  'class-12/books/punjab-board-chemistry',
  'class-12/books/punjab-board-biology',
  'class-12/books/punjab-board-math',
  'class-12/books/punjab-board-computer-science',
  'class-12/books/punjab-board-english',
  'class-12/books/punjab-board-pak-study',
  'class-12/books/punjab-board-tarjuma-tul-quran',
  'class-12/books/punjab-board-urdu',

  'class-12/date-sheet',
  'class-12/date-sheet/bahawalpur-board',
  'class-12/date-sheet/dg-khan-board',
  'class-12/date-sheet/faisalabad-board',
  'class-12/date-sheet/gujranwala-board',
  'class-12/date-sheet/lahore-board',
  'class-12/date-sheet/multan-board',
  'class-12/date-sheet/rawalpindi-board',
  'class-12/date-sheet/sahiwal-board',
  'class-12/date-sheet/sargodha-board',

  'class-12/notes',
  'class-12/notes/punjab-board-physics',
  'class-12/notes/punjab-board-chemistry',
  'class-12/notes/punjab-board-biology',

  'class-12/online-test',
  'class-12/online-test/physics',
  'class-12/online-test/physics/chapter-1',
  'class-12/online-test/physics/chapter-2',
  'class-12/online-test/physics/chapter-3',
  'class-12/online-test/physics/chapter-4',
  'class-12/online-test/physics/chapter-5',
  'class-12/online-test/physics/chapter-6',
  'class-12/online-test/physics/chapter-7',
  'class-12/online-test/physics/chapter-8',
  'class-12/online-test/physics/chapter-9',
  'class-12/online-test/physics/chapter-10',
  'class-12/online-test/biology',
  'class-12/online-test/biology/chapter-1',
  'class-12/online-test/biology/chapter-2',
  'class-12/online-test/biology/chapter-3',
  'class-12/online-test/biology/chapter-4',
  'class-12/online-test/biology/chapter-5',
  'class-12/online-test/biology/chapter-6',
  'class-12/online-test/biology/chapter-7',
  'class-12/online-test/biology/chapter-8',
  'class-12/online-test/biology/chapter-9',
  'class-12/online-test/biology/chapter-10',
  'class-12/online-test/biology/chapter-11',
  'class-12/online-test/biology/chapter-12',
  'class-12/online-test/biology/chapter-13',
  'class-12/online-test/chemistry',
  'class-12/online-test/chemistry/chapter-1',
  'class-12/online-test/chemistry/chapter-2',
  'class-12/online-test/chemistry/chapter-3',
  'class-12/online-test/chemistry/chapter-4',
  'class-12/online-test/chemistry/chapter-5',
  'class-12/online-test/chemistry/chapter-6',
  'class-12/online-test/chemistry/chapter-7',
  'class-12/online-test/chemistry/chapter-8',
  'class-12/online-test/chemistry/chapter-9',
  'class-12/online-test/chemistry/chapter-10',
  'class-12/online-test/chemistry/chapter-11',
  'class-12/online-test/chemistry/chapter-12',
  'class-12/online-test/chemistry/chapter-13',
  'class-12/online-test/chemistry/chapter-14',
  'class-12/online-test/chemistry/chapter-15',
  'class-12/online-test/chemistry/chapter-16',

  'class-12/pairing-scheme',
  'class-12/pairing-scheme/punjab-board',
  'class-12/pairing-scheme/punjab-board/biology',
  'class-12/pairing-scheme/punjab-board/chemistry',
  'class-12/pairing-scheme/punjab-board/physics',
  'class-12/pairing-scheme/punjab-board/math',

  'class-12/past-paper',
  'class-12/past-paper/faisalabad-board-biology',
  'class-12/past-paper/faisalabad-board-chemistry',
  'class-12/past-paper/faisalabad-board-physics',
  'class-12/past-paper/lahore-board-biology',
  'class-12/past-paper/lahore-board-chemistry',
  'class-12/past-paper/lahore-board-physics',

  'class-12/result',
  'class-12/result/bahawalpur-board',
  'class-12/result/dg-khan-board',
  'class-12/result/faisalabad-board',
  'class-12/result/gujranwala-board',
  'class-12/result/lahore-board',
  'class-12/result/multan-board',
  'class-12/result/rawalpindi-board',
  'class-12/result/sahiwal-board',
  'class-12/result/sargodha-board',
];

const vuroute = [
  'vu/handouts',

  'vu/handouts/cs001',
  'vu/handouts/cs101',
  'vu/handouts/cs201',
  'vu/handouts/cs202',
  'vu/handouts/cs205',
  'vu/handouts/cs206',
  'vu/handouts/cs301',
  'vu/handouts/cs302',
  'vu/handouts/cs304',
  'vu/handouts/cs310',
  'vu/handouts/cs311',
  'vu/handouts/cs312',
  'vu/handouts/cs315',
  'vu/handouts/cs401',
  'vu/handouts/cs402',
  'vu/handouts/cs403',
  'vu/handouts/cs405',
  'vu/handouts/cs407',
  'vu/handouts/cs408',
  'vu/handouts/cs410',
  'vu/handouts/cs411',
  'vu/handouts/cs432',
  'vu/handouts/cs435',
  'vu/handouts/cs506',
  'vu/handouts/cs508',
  'vu/handouts/cs602',
  'vu/handouts/cs607',

  'vu/handouts/edu201',
  'vu/handouts/edu301',
  'vu/handouts/edu401',
  'vu/handouts/edu406',

  'vu/handouts/eng101',
  'vu/handouts/eng201',
  'vu/handouts/eng301',
  'vu/handouts/eng401',
  'vu/handouts/eng406',

  'vu/handouts/mgt211',

  'vu/handouts/mth001',
  'vu/handouts/mth100',
  'vu/handouts/mth101',
  'vu/handouts/mth102',
  'vu/handouts/mth201',
  'vu/handouts/mth202',
  'vu/handouts/mth301',
  'vu/handouts/mth302',
  'vu/handouts/mth303',
  'vu/handouts/mth401',
  'vu/handouts/mth501',
  'vu/handouts/mth601',
  'vu/handouts/mth603',
  'vu/handouts/mth621',
  'vu/handouts/mth622',
  'vu/handouts/mth631',
  'vu/handouts/mth632',
  'vu/handouts/mth633',
  'vu/handouts/mth634',
  'vu/handouts/mth641',
  'vu/handouts/mth701',
  'vu/handouts/mth706',
  'vu/handouts/mth7123',
  'vu/handouts/mth718',
  'vu/handouts/mth721',

  'vu/handouts/pak301',
  'vu/handouts/pak302',

  'vu/handouts/phy101',
  'vu/handouts/phy301',

  'vu/highlight-handouts',
  'vu/mid-mark-calculator',
  'vu/final-mcqs',
  'vu/mid-mcqs',
];

const data = [
  ...singleroute,
  ...class9route,
  ...class10route,
  ...class11route,
  ...class12route,
  ...vuroute,
];

// Assign the combined data to SitemapUrl
const SitemapUrl = data;

export { SitemapUrl };
