export * from './board.seeder';
export * from './book.seeder';
export * from './chapter.seeder';
export * from './class.seeder';
export * from './heading.seeder';
export * from './mcqs.seeder';
export * from './service.seeder';
export * from './subHeading.seeder';
export * from './user.seeder';
