export { authRouter } from './auth.router';
export { boardRouter } from './board/board.router';
export { bookRouter } from './book/book.router';
export { chapterRouter } from './chapter/chapter.router';
export { classRouter } from './class/class.router';
export { classGroupRouter } from './classGroup.router';
export { feedbackRouter } from './feedback.router';
export { commentRouter } from './comment.router';
export { headingRouter } from './heading/heading.router';
export { institutionRouter } from './institution.router';
export { mcqAttemptRouter } from './mcqAttempt.router';
export { mcqsRouter } from './mcqs.router';
export { serviceRouter } from './service/service.router';
export { studentRouter } from './student.router';
export { subHeadingRouter } from './subHeading/subHeading.router';
export { authRouter as userAuthRouter } from './user.router';
